export default {
  cocktails: [
    {
      name: "Brasilian Sunrise",
      description: "",
      alcohol: false,
      recipe: {
        Cachaça: "4cl",
        Orangensaft: "10cl",
        Zitronensaft: "1cl",
        Grenadine: "2cl",
      },
      image: "brasilianSunrise.webp",
      category: ["pitu"],
    },
    {
      name: "Batida Mango",
      description: "",
      alcohol: false,
      recipe: {
        Cachaça: "4cl",
        Orangensaft: "10cl",
        "Mango Sirup": "3cl",
        Zitronensaft: "1cl",
      },
      image: "batidaMango.webp",
      category: ["pitu", "classic"],
    },
    {
      name: "Red Rose",
      description: "",
      alcohol: false,
      recipe: {
        "Tonic Water": "11cl",
        Zitronensaft: "1cl",
        Traubensaft: "6cl",
        Erdbeersirup: "2cl",
      },
      image: "redRose.webp",
      category: ["alcoholFree", "classic"],
    },
    {
      name: "Wodka Wild Berry",
      description: "",
      alcohol: 8,
      recipe: {
        Wodka: "4cl",
        "Wild Berry": "16cl",
      },
      image: "wodkaWildBerry.webp",
      category: ["wodka"],
    },
    {
      name: "Wodka Lemon",
      description: "",
      alcohol: 8,
      recipe: {
        Wodka: "4cl",
        "Bitter Lemon": "16cl",
      },
      image: "wodkaLemon.webp",
      category: ["wodka", "classic"],
    },
    {
      name: "Graperol",
      description: "",
      alcohol: true,
      recipe: {
        Aperol: "4cl",
        Traubensaft: "4cl",
        Soda: "4cl",
      },
      image: "graperol.webp",
      category: ["aperol"],
    },
    {
      name: "Aperol Lemon Spritz",
      description: "",
      alcohol: 3,
      recipe: {
        Aperol: "4cl",
        "Bitter Lemon": "16cl",
      },
      image: "aperolLemonSpritz.webp",
      category: ["aperol"],
    },

    {
      name: "Aperol Orange Spritz",
      description: "",
      alcohol: true,
      recipe: {
        Aperol: "4cl",
        Orangensaft: "4cl",
        Soda: "4cl",
      },
      image: "aperolOrangeSpritz.webp",
      category: ["aperol"],
    },
    {
      name: "Aperol Spritz",
      description: "",
      alcohol: true,
      recipe: {
        Aperol: "4cl",
        Prosecco: "6cl",
        Soda: "2cl",
      },
      image: "aperolSpritz.webp",
      category: ["aperol", "classic"],
    },
    {
      name: "Pink Gin",
      description: "",
      alcohol: 8,
      recipe: {
        Gin: "4cl",
        "Wild Berry": "16cl",
      },
      image: "pinkGin.webp",
      category: ["gin"],
    },
    {
      name: "Gin Tonic",
      description: "",
      alcohol: 8,
      recipe: {
        Gin: "4cl",
        "Tonic Water": "16cl",
      },
      image: "ginTonic.webp",
      category: ["gin", "classic"],
    },
    {
      name: "Tom Collins ",
      description: "",
      alcohol: 8,
      recipe: {
        Gin: "5cl",
        Soda: "10cl",
        Zitronensaft: "3cl",
        Zuckersirup: "2cl",
      },
      image: "tomCollins.webp",
      category: ["gin", "classic"],
    },
  ],
};
